name: sanitize_filename
description: Replaces characters in strings that are illegal/unsafe for filenames.
version: 1.0.1
homepage: https://github.com/egomobile/sanitize_filename

environment:
  sdk: '>=2.17.1 <3.0.0'

dev_dependencies:
  lints: ^2.0.0
  test: ^1.16.0
