name: Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: google/dart:2.17-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: Setup credentials
        run: | 
          mkdir -p ~/.pub-cache 
          cat <<EOF > ~/.pub-cache/credentials.json
          {
            "accessToken":"${{ secrets.PUB_DEV_ACCESS_TOKEN }}",
            "refreshToken":"${{ secrets.PUB_DEV_REFRESH_TOKEN }}",
            "tokenEndpoint": "https://accounts.google.com/o/oauth2/token"
            "scopes": [ "openid", "https://www.googleapis.com/auth/userinfo.email" ],
            "expiration": 1655837829848
          }
          EOF
      - name: Publish package
        run: dart pub publish -f
