name: Publish

on:
  push:
    branches:
      - master

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    container:
      image: google/dart:latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
      - name: 'Publish package'
        uses: k-paxian/dart-package-publisher@master
        with:
          accessToken: ${{ secrets.PUB_DEV_ACCESS_TOKEN }}
          refreshToken: ${{ secrets.PUB_DEV_REFRESH_TOKEN }}
