name: Check pull requests

on:
  pull_request:
    types: ["opened", "edited", "reopened", "synchronize"]

jobs:
  check-pr:
    runs-on: ubuntu-latest
    container:
      image: dart:2.17-sdk
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Install dependencies
        run: dart pub get
      - name: Run tests
        run: dart test
